#!/bin/sh
eval "$(conda shell.bash hook)"
conda activate tfvenv2
python ExperimentsFrame.py waveform_noise 25 1
python ExperimentsFrame.py waveform_noise 50 1
python ExperimentsFrame.py waveform_noise 100 1
python ExperimentsFrame.py waveform_noise 150 1
python ExperimentsFrame.py waveform_noise 200 1
conda deactivate