#!/bin/sh
eval "$(conda shell.bash hook)"
conda activate tfvenv2
python ExperimentsFrame.py waveform_noise 25 2
python ExperimentsFrame.py waveform_noise 50 2
python ExperimentsFrame.py waveform_noise 100 2
python ExperimentsFrame.py waveform_noise 150 2
python ExperimentsFrame.py waveform_noise 200 2
conda deactivate