#!/bin/sh
eval "$(conda shell.bash hook)"
conda activate tfvenv2
python ExperimentsFrame.py waveform_noise 25 3
python ExperimentsFrame.py waveform_noise 50 3
python ExperimentsFrame.py waveform_noise 100 3
python ExperimentsFrame.py waveform_noise 150 3
python ExperimentsFrame.py waveform_noise 200 3
conda deactivate