#!/bin/sh
eval "$(conda shell.bash hook)"
conda activate tfvenv2
python ExperimentsFrame.py waveform_noise 25 4
python ExperimentsFrame.py waveform_noise 50 4
python ExperimentsFrame.py waveform_noise 100 4
python ExperimentsFrame.py waveform_noise 150 4
python ExperimentsFrame.py waveform_noise 200 4
conda deactivate